# -*- coding: utf-8 -*-
"""CREDIT SCORING MODEL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAqX0sBGuKcAqJoH_JbHy7_BpYVrSujE

# CREDIT SCORING MODEL

CONTRIBUTION: Vinay_Raj_Singh

**Project Description** - Banks and credit card companies calculate the credit score to determine the creditworthiness. It helps banks and credit card companies immediately to issue loans to customers with good creditworthiness. Objective of this project is to build a machine learning model that can predict whether customer will get loan or not based on their credit history.
"""

# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
import json
import os
import pickle
warnings.filterwarnings('ignore')

# load the dataset
df = pd.read_csv('train_set.csv')

# information
df.info()

# sample rows
df.head()

# description
df.describe()

"""# Knowing your variables:"""

# check for null/missing values
df.isnull().sum()

# fill the missing values
df['Credit_Mix'] = df['Credit_Mix'].fillna(df['Credit_Mix'].mode()[0])

# remove the null values
df.dropna(inplace=True)

# numeric columns detection
df.select_dtypes(include='number').columns

# categorical columns detection
df.select_dtypes(include='object').columns

"""# EXPLORATORY DATA ANALYSIS(EDA):"""

# histogram plot
fig = px.bar(x='Age', y='Num_of_Loan', data_frame=df, color='Num_of_Loan')
fig.show()

# scatter plot
fig = px.scatter(x='Annual_Income', y='Credit_History_Age', data_frame=df, color='Num_of_Loan')
fig.show()

# box plot
fig = px.box(x='Month', y='Amount_invested_monthly', data_frame=df, color='Num_of_Loan')
fig.show()

# heatmap correlation
fig = px.show(df.select_dtypes(include='number').corr())
fig.show()

# credit score based on occupation
fig = px.box(df,
             x="Occupation",
             color="Credit_Score",
             title="Credit Scores Based on Occupation",
             color_discrete_map={'Poor':'red',
                                 'Standard':'yellow',
                                 'Good':'green'})
fig.show()

# credit score based on annual income
fig = px.box(df,
             x="Annual_Income",
             color="Credit_Score",
             title="Credit Scores Based on Annual Income",
             color_discrete_map={'Poor':'red',
                                 'Standard':'yellow',
                                 'Good':'green'})
fig.show()



"""# MODEL SELECTION:

# RANDOM FOREST:
"""

# RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# test and train
X = df.drop('Credit_Score', axis=1)
y = df['Credit_Score']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Identify categorical columns
categorical_cols = X_train.select_dtypes(include='object').columns

# Create a ColumnTransformer to apply one-hot encoding
preprocessor = ColumnTransformer(
    transformers=[
        ('one_hot', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ],
    remainder='passthrough'
)

# Apply the preprocessor to the training and testing data
X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

# random forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train_encoded, y_train)

# predict
y_pred = rf.predict(X_test_encoded)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

"""# XG boost:"""

# XGBoost
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

# train, test and split
X = df.drop('Credit_Score', axis=1)
y = df['Credit_Score']

# Encode the target variable
le = LabelEncoder()
y_encoded = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# identify categorical columns
categorical_cols = X_train.select_dtypes(include='object').columns

# Create a ColumnTransformer to apply one-hot encoding
preprocessor = ColumnTransformer(
    transformers=[
        ('one_hot', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ],
    remainder='passthrough'
)

# Apply the preprocessor to the training and testing data
X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

# xg boost
xgb_model = xgb.XGBClassifier(n_estimators=100, random_state=42)
xgb_model.fit(X_train_encoded, y_train)

# predict
y_pred = xgb_model.predict(X_test_encoded)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred, target_names=le.classes_)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

"""# LIGHT GBM:"""

# light gbm
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

# train, test and split
X = df.drop('Credit_Score', axis=1)
y = df['Credit_Score']

# Encode the target variable
le = LabelEncoder()
y_encoded = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# identify categorical columns
categorical_cols = X_train.select_dtypes(include='object').columns

# Create a ColumnTransformer to apply one-hot encoding
preprocessor = ColumnTransformer(
    transformers=[
        ('one_hot', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ],
    remainder='passthrough'
)

# Apply the preprocessor to the training and testing data
X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

# light gbm
lgb_model = lgb.LG_BMClassifier(n_estimators=100, random_state=42)
lgb_model.fit(X_train_encoded, y_train)

# FIXED: was incorrectly using xgb_model instead of lgb_model
y_pred = lgb_model.predict(X_test_encoded)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred, target_names=le.classes_)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

"""# SHAP:"""

import warnings as shap_warnings
shap_warnings.filterwarnings("ignore")

import pickle
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, RandomizedSearchCV
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, HistGradientBoostingClassifier
from sklearn.metrics import roc_auc_score, roc_curve, classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import json

# ---------------------------
# Config
# ---------------------------
DATA_PATH = "train_set.csv"   # change if needed
RANDOM_STATE = 42
TEST_SIZE = 0.30
CV_FOLDS = 3
RANDOM_SEARCH_ITERS = 10   # tune down/up depending on time/compute
OUTPUT_MODEL_PATH = "best_model.pkl"
OUTPUT_META_PATH = "meta.json"

# ---------------------------
# Load data
# ---------------------------
df = pd.read_csv('train_set.csv')
print("Loaded:", DATA_PATH, "shape:", df.shape)
print("Columns:", list(df.columns)[:30])

# ---------------------------
# Target detection + robust conversion to binary
# ---------------------------
preferred_names = {'target','default','loan_status','loan_default','y','is_default','approved','status','credit_default'}
found = None
for c_and in preferred_names:
    if c_and in df.columns:
        found = c_and
        break
if found is None:
    # fallback: last column
    found = df.columns[-1]
print("Using target column:", found)

y_raw = df[found]

# convert textual labels to lower-case stripped strings for matching
if y_raw.dtype == 'O' or y_raw.nunique() <= 10:
    unique_vals = [str(v).strip().lower() for v in y_raw.dropna().unique()]
    bad_keywords = ['poor', 'bad', 'low', 'delinq', 'delinquent', 'default', 'rejected', 'no', 'denied', 'declined', 'fraud']
    # if any of the unique label strings contains a bad keyword, map heuristically
    if any(any(k in uv for k in bad_keywords) for uv in unique_vals):
        mapping = {}
        for uv in unique_vals:
            mapping[uv] = 0 if any(k in uv for k in bad_keywords) else 1
        y = y_raw.astype(str).str.strip().str.lower().map(mapping).fillna(0).astype(int)
        print("Mapped target by keyword heuristic. Example mapping:", dict(list(mapping.items())[:10]))
    else:
        # fallback: factorize and median-split
        fac, uniques = pd.factorize(y_raw.astype(str))
        cut = np.nanmedian(fac)
        y = (fac >= cut).astype(int)
        print("Target factorized and median-split. Unique categories:", uniques)
else:
    # numeric target -> threshold at median
    try:
        y_num = pd.to_numeric(y_raw, errors='coerce')
        median_val = y_num.median()
        y = (y_num >= median_val).astype(int)
        print("Numeric target threshold at median:", median_val)
    except Exception:
        # fallback
        y = pd.to_numeric(y_raw, errors='coerce').fillna(0).astype(int)

print("Target distribution:\n", y.value_counts())

# ---------------------------
# Prepare features (drop ID-like columns)
# ---------------------------
X = df.drop(columns=[found])

id_like = [c for c in X.columns if any(k in c.lower() for k in ['id','ssn','name','customer','account'])]
if len(id_like) > 0:
    print("Dropping ID-like columns:", id_like)
    X = X.drop(columns=id_like, errors='ignore')

# Identify numeric vs categorical
num_cols = X.select_dtypes(include=['number']).columns.tolist()
cat_cols = X.select_dtypes(include=['object','category','bool']).columns.tolist()
# move small-cardinality integer columns to categorical (often they are codes)
for c in num_cols.copy():
    if X[c].nunique() <= 10 and str(X[c].dtype).startswith('int'):
        cat_cols.append(c)
        num_cols.remove(c)

print(f"Numeric features: {len(num_cols)}, Categorical features: {len(cat_cols)}")

# ---------------------------
# Preprocessing pipelines
# ---------------------------
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('one_hot', OneHotEncoder(handle_unknown='ignore'))
])
preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, num_cols),
    ('cat', categorical_transformer, cat_cols)
], remainder='drop')

# Save metadata for the Streamlit app
meta = {
    "model": "",
    "classes": [],
    "numeric": num_cols,
    "categorical": cat_cols
}

# ---------------------------
# Train/test split
# ---------------------------
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_SIZE, stratify=y, random_state=RANDOM_STATE)
print("Train/test shapes:", X_train.shape, X_test.shape)

# ---------------------------
# Define candidate models
# ---------------------------
models = {
    "LogisticRegression": Pipeline([('pre', preprocessor), ('clf', LogisticRegression(max_iter=1000, random_state=RANDOM_STATE))]),
    "RandomForest": Pipeline([('pre', preprocessor), ('clf', RandomForestClassifier(n_estimators=100, n_jobs=1, random_state=RANDOM_STATE))]),
    "GradientBoosting": Pipeline([('pre', preprocessor), ('clf', GradientBoostingClassifier(n_estimators=100, random_state=RANDOM_STATE))]),
    "HistGradientBoosting": Pipeline([('pre', preprocessor), ('clf', HistGradientBoostingClassifier(max_iter=100, random_state=RANDOM_STATE))])
}

# Optional: add XGBoost if installed
try:
    import xgboost as xgb
    models["XGBoost"] = Pipeline([('pre', preprocessor), ('clf', xgb.XGBClassifier(n_estimators=100, eval_metric='logos', random_state=RANDOM_STATE, n_jobs=1))])
    print("XGBoost is available and included in comparison.")
except Exception:
    print("XGBoost not available — you can install xgboost to include it.")

# ---------------------------
# Compare models by CV AUC
# ---------------------------
cv = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=RANDOM_STATE)
model_scores = []
for name, pipe in models.items():
    try:
        scores = cross_val_score(pipe, X_train, y_train, cv=cv, scoring='roc_auc', n_jobs=1)
        model_scores.append((name, scores.mean(), scores.std()))
        print(f"{name}: CV AUC = {scores.mean():.4f} ± {scores.std():.4f}")
    except Exception as e:
        print("Failed to evaluate", name, "->", e)

scores_df = pd.DataFrame(model_scores, columns=['model', 'mean_auc', 'std_auc']).sort_values('mean_auc', ascending=False).reset_index(drop=True)
print("\nModel ranking by CV AUC:\n", scores_df)

best_model_name = scores_df.loc[0, 'model']
print("Selected best model:", best_model_name)

# ---------------------------
# Hyperparameter tuning (small randomized search) on the chosen model
# ---------------------------
best_pipeline = models[best_model_name]
param_distributions = {}

if best_model_name == "RandomForest":
    param_distributions = {
        'clf__n_estimators': [100, 200, 400],
        'clf__max_depth': [None, 10, 20],
        'clf__min_samples_split': [2, 5, 10]
    }
elif best_model_name == "GradientBoosting":
    param_distributions = {
        'clf__n_estimators': [100, 200, 400],
        'clf__learning_rate': [0.01, 0.05, 0.1],
        'clf__max_depth': [3, 5, 8]
    }
elif best_model_name == "HistGradientBoosting":
    param_distributions = {
        'clf__max_iter': [100, 200, 400],
        'clf__learning_rate': [0.01, 0.05, 0.1],
        'clf__max_depth': [3, 5, 8]
    }
elif best_model_name == "XGBoost":
    param_distributions = {
        'clf__n_estimators': [100, 200, 400],
        'clf__learning_rate': [0.01, 0.05, 0.1],
        'clf__max_depth': [3, 5, 7]
    }
elif best_model_name == "LogisticRegression":
    param_distributions = {
        'clf__C': [0.01, 0.1, 1, 10],
        'clf__penalty': ['l2']
    }

if param_distributions:
    rs = RandomizedSearchCV(best_pipeline, param_distributions, n_iter=min(RANDOM_SEARCH_ITERS, 20),
                            scoring='roc_auc', cv=cv, n_jobs=1, random_state=RANDOM_STATE, verbose=1)
    print("Starting RandomizedSearchCV on", best_model_name)
    rs.fit(X_train, y_train)
    print("Best params:", rs.best_params_)
    final_model = rs.best_estimator_
else:
    print("No hyperparameters defined for tuning; fitting selected model without tuning.")
    final_model = best_pipeline.fit(X_train, y_train)

# ---------------------------
# Evaluate on test set
# ---------------------------
y_pred = final_model.predict(X_test)
try:
    y_proba = final_model.predict_proba(X_test)[:, 1]
except Exception:
    # fallback to decision_function
    try:
        df_scores = final_model.decision_function(X_test)
        y_proba = (df_scores - df_scores.min()) / (df_scores.max() - df_scores.min())
    except Exception:
        y_proba = np.zeros(len(y_test))

auc = roc_auc_score(y_test, y_proba)
acc = accuracy_score(y_test, y_pred)
print(f"\nTest AUC: {auc:.4f} | Test Accuracy: {acc:.4f}\n")
print("Classification report:")
print(classification_report(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

# ROC curve
fpr, tpr, _ = roc_curve(y_test, y_proba)
plt.figure(fig__size=(6,5))
plt.plot(fpr, tpr)
plt.plot([0,1], [0,1], '--')
plt.title(f"ROC - {best_model_name} (AUC = {auc:.3f})")
plt.x_label("False Positive Rate"); plt.y_label("True Positive Rate")
plt.grid(True); plt.tight_layout()
plt.show()

# ---------------------------
# Save model
# ---------------------------
with open(OUTPUT_MODEL_PATH, "wb") as f:
    pickle.dump(final_model, f)
print("Saved final model to:", OUTPUT_MODEL_PATH)

# ---------------------------
# Save metadata for Streamlit app
# ---------------------------
meta["model"] = best_model_name
# Store target classes from the model (binary: 0 and 1)
meta["classes"] = sorted([str(c) for c in final_model.classes_])
with open(OUTPUT_META_PATH, "w") as f:
    json.dump(meta, f)
print("Saved metadata to:", OUTPUT_META_PATH)

# ---------------------------
# Useful next steps (not executed):
#  - Calibrate probabilities (CalibratedClassifierCV) if you need well-calibrated scores
#  - Use class_weight or sampling or cost-sensitive learning if class imbalance and business costs matter
#  - Use SHAP for interpretability: pip install shap ; use shap.TreeExplainer for tree models
#  - Consider LightGBM/CatBoost if you want faster training or better handling of categorical
#  - Persist preprocessing separately (save the pipeline) & build a small scoring API for deployment
# ---------------------------

"""# BUILD UI USING STREAMLIT:

# DEPLOYMENT:
"""


"""
app_multi_class_shap.py

Streamlit app for multi_class credit scoring with SHAP explainability.
Run: streamlit run app_multi_class_shap.py
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
import json
import os
import shap
import matplotlib.pyplot as plt

st.set_page_config(page_title="💳 Credit Scoring AI Dashboard", layout="wide", page_icon="💳")

# ---------------------------
# Load model & metadata
# ---------------------------
MODEL_PATH = "best_model.pkl"
META_PATH = "meta.json"

st.markdown(
    """
    <style>
    .good {background-color:#4CAF50;color:white;padding:15px;border-radius:10px;text-align:center;font-size:24px;}
    .standard {background-color:#FFC107;color:black;padding:15px;border-radius:10px;text-align:center;font-size:24px;}
    .poor {background-color:#F44336;color:white;padding:15px;border-radius:10px;text-align:center;font-size:24px;}
    </style>
    """,
    unsafe_allow_html=True
)

st.title("💳 Credit Scoring Prediction with Explainability")
st.markdown("### Predict and interpret a customer's **Credit Score Category** — `Poor`, `Standard`, or `Good`.")

if not os.path.exists(MODEL_PATH) or not os.path.exists(META_PATH):
    st.error("❌ Model or metadata not found. Please train using `train_model_multi_class.py` first.")
    st.stop()

with open(MODEL_PATH, "rb") as f:
    model = pickle.load(f)
with open(META_PATH, "r") as f:
    meta = json.load(f)

classes = meta["classes"]
num_cols = meta["numeric"]
cat_cols = meta["categorical"]

# ---------------------------
# Sidebar Input Form
# ---------------------------
st.sidebar.header("🧮 Enter Customer Details")

def get_inputs():
    data = {}
    st.sidebar.subheader("Numeric Features")
    for col in num_cols:
        data[col] = st.sidebar.number_input(col, step=0.01, value=0.0)

    if cat_cols:
        st.sidebar.subheader("Categorical Features")
        for col in cat_cols:
            data[col] = st.sidebar.text_input(col, value="")
    return pd.DataFrame([data])

user_df = get_inputs()

# ---------------------------
# Prediction Section
# ---------------------------
col1, col2 = st.columns([2, 1])

with col1:
    st.subheader("📊 Prediction Result")

    if st.sidebar.button("🚀 Predict Credit Score"):
        try:
            preds = model.predict(user_df)[0]
            probs = model.predict_proba(user_df)[0]
            prob_df = pd.DataFrame({"Class": classes, "Probability": probs}).sort_values("Probability", ascending=False)

            top_class = prob_df.iloc[0]["Class"]

            # Color-coded card
            if top_class.lower() == "good":
                st.markdown(f"<div class='good'>✅ Credit Score: {top_class}</div>", unsafe_allow_html=True)
            elif top_class.lower() == "standard":
                st.markdown(f"<div class='standard'>⚖️ Credit Score: {top_class}</div>", unsafe_allow_html=True)
            else:
                st.markdown(f"<div class='poor'>❌ Credit Score: {top_class}</div>", unsafe_allow_html=True)

            # Show probability bars
            st.markdown("### 🔍 Prediction Probabilities")
            for _, row in prob_df.iterrows():
                st.write(f"**{row['Class']}** ({row['Probability']:.2%})")
                st.progress(row["Probability"])

            # ---------------------------
            # SHAP Explainability
            # ---------------------------
            st.markdown("---")
            st.subheader("🧠 Explain Prediction with SHAP")

            try:
                # Get model and preprocessor
                preprocessor = model.named_steps["pre"]
                clf = model.named_steps["clf"]

                X_trans = preprocessor.transform(user_df)

                # Use TreeExplainer for tree-based models, otherwise KernelExplainer
                if hasattr(clf, 'feature_importance_') or 'tree' in str(type(clf)).lower():
                    explainer = shap.TreeExplainer(clf)
                    shap_values = explainer.shap_values(X_trans)

                    st.markdown("#### 🔎 Individual Feature Contributions")
                    fig, ax = plt.subplots(fig_size=(10, 5))
                    shap.force_plot(explainer.expected_value, shap_values[0], X_trans, matplotlib=True, show=False)
                    st.pyplot(fig)
                    plt.close(fig)

                    # Summary bar
                    st.markdown("#### 📈 Global Feature Importance")
                    fig2, ax2 = plt.subplots(fig_size=(10, 6))
                    shap.summary_plot(shap_values, X_trans, plot_type="bar", show=False)
                    st.pyplot(fig2)
                    plt.close(fig2)
                else:
                    st.info("ℹ️ SHAP explanation is only available for tree-based models in this app. The selected model is not tree-based.")

            except Exception as e:
                st.warning(f"⚠️ SHAP explanation not available for this model type: {e}")

        except Exception as e:
            st.error(f"Prediction failed: {e}")

    else:
        st.info("👈 Enter inputs and click **Predict Credit Score** to get results and SHAP explanations.")

with col2:
    st.image("https://cdn-icons-png.flaticon.com/512/2920/2920244.png", width=220)
    st.markdown("#### Model Information")
    st.json({
        "Trained Model": meta["model"],
        "Target Classes": meta["classes"],
        "Numeric Features": len(meta["numeric"]),
        "Categorical Features": len(meta["categorical"])
    })

st.markdown("---")
st.caption("Built with ❤️ using Streamlit + SHAP | Multi_class Credit Scoring AI App")

"""# CONCLUSION:"""
